### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [oscarjes/DuckSocial#1]
Fabulous!! Could you do me a favor and split into Required and Optional user stories in your README.md? :)

**Comment by oscarjes** [comment]
Done!

**Comment by coderschoolreview** [comment]
Thanks for the fantastic submission. Always a pleasure reviewing your work 🎊

## Great things

- Clean routes for, with good use of `only` and `except`
- Nice terminology and setup for WallPost and WallMention. Great use of optional `mentioned_id` in WallPost
- Nice use of `require_login` and `skip_if_logged_in` in UsersController and SessionsController. Note you may want similar uses in the other controllers.
- Use of URL validation in User model

## Suggestions / Area to Imrpove

- You can your `find_by` with `.where` when appropriate (when dealing with more than one result)
- In `users/find.html.erb`: Don't use `button_to` inside a `form_for` or `form_tag` because button_to already generates a form element itself ([docs](http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-button_to))
- Consider using partials to share code between `users/index.html.erb` and `users/find.html.erb`. HTML indentation is also messy in these two files.
- Move `user_params` method to the bottom of `UsersController` and put it under the keyword `private` to distinguish it from actions
- Add `before_action :require_user` in WallPostsController to prevent the page from crashing when a guest visits the page.
- Refactoring

```
# BEFORE
  def self.friended_by_count(user)
    list = []
    list << find_by(friend_id: user.id)
    if list == [nil]
      "0"
    else
      list.length
    end
  end

# AFTER
def self.friended_by_count(user)
  Friendship.where(friend: user).count
end
```

- You don't need two separate `User.generate_male_users` and `User.generate_female_users` methods. You can call `User.generate_users(5, "male")` and `User.generate_user(5, "female")`
- I'm a little confused by your `User#added_as_friend_count(user)` method. Shouldn't it be only one friendship?

Once again, we'd love to include your GIF in the sample submissions for the future class (if that's a problem, just let us know). Good luck with the fun social features this week.

**Comment by coderschoolreview** [comment]
great submission as usual. just a quick note: i think there's a bug with updating my profile picture. i sign up without one and now after uploading an image i still don't have the picture.

**Comment by oscarjes** [comment]
Thanks! I looked into it and it seems that the issue is caused when there's a slow internet connection. AWS doesn't get the image then and it takes a while. Otherwise it seems to work:

https://cl.ly/m9a0
